CREATE SCHEMA IF NOT EXISTS test;

CREATE TABLE IF NOT EXISTS test.table1 (
  id INT PRIMARY KEY,
  thing VARCHAR
);

INSERT INTO TEST.TABLE1 (ID, THING) VALUES (1, 'test');

SELECT * FROM TEST.TABLE1;